### ISSUE TITLE
General directions

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/zcashfoundation.github.io#14]
- [x] Ensure that all relevant Markdown files at https://github.com/ZcashFoundation/ are also available on the ZCF website.
- [x] Base work on the existing https://github.com/ZcashFoundation/zcashfounda- tion.github.io repository and website.
- [x] Rework the structure based on the proposed structure.
- [x] Ensure that the site is fast-loading, with minimal dependencies, and ease of maintenance.
- [ ] Provide clear publishing and maintenance instructions and guides for future web developers and content managers.
- [ ] Ensure that existing links to website or GitHub documents don’t break, as much as possible. Archive repositories or documents, and/or suggest redirects for existing links on GitHub to the new website as needed.
